### PR TITLE
26122791: Template - Header

### PR DESCRIPTION
**Pull request by jasonrsavino**
## Description
As a user of the Roosevelt site, I need an easy and intuitive way to navigate, search and have the same look and feel through the website, so I can quickly find what I’m looking for.

## Acceptance Criteria
- [ ] Logo should be on the header (Desktop & Mobile)
- [ ] The main menu can have up to two levels w/group title for each submenu (Desktop & Mobile)
- [ ] The main menu should act as mega-menu (Desktop)
- [ ] Utility menu has only one level (Desktop & Mobile)
- [ ] Search option should expand/collapse when clicked - refer to design (Desktop/Mobile)
- [ ] Sticky header (Desktop and Mobile)
- [ ] Mobile merge main menu and utility menu (Mobile)
- [ ] Mobile stacks menu option, logo and search (Mobile)
- [ ] Header has to match the design (Desktop & Mobile)
- [ ] Accessibility check

## Affected URL
[Full site](http://pr-71-rooseveltedu.pantheonsite.io/)

## Related Tickets
* [Template - Header - Desktop - Logo](https://kanopi.teamwork.com/#/tasks/26122795)
* [Template - Header - Mobile - Logo](https://kanopi.teamwork.com/#/tasks/26124946)
* [Template - Header - Desktop - Main Menu](https://kanopi.teamwork.com/#/tasks/26122796)
* [Template - Header - Mobile - Main Menu](https://kanopi.teamwork.com/#/tasks/26124947)
* [Template - Header - Mobile - Utility Menu](https://kanopi.teamwork.com/#/tasks/26124948)
* [Template - Header - Desktop - Utility Menu](https://kanopi.teamwork.com/#/tasks/26122797)
* [Template - Header - Desktop - Search Widget](https://kanopi.teamwork.com/#/tasks/26122799)
* [Template - Header - Mobile - Search Widget](https://kanopi.teamwork.com/#/tasks/26124950)
* [Template - Header - templating/style miscellaneous](https://kanopi.teamwork.com/#/tasks/26124945)
* [Template - Header - Desktop - Sticky menu & transition](https://kanopi.teamwork.com/#/tasks/26122800)
* [Template - Header - Mobile - Sticky menu & transition](https://kanopi.teamwork.com/#/tasks/26124951)

## Steps to Validate
1. Navigate to website
1. See global header
1. Click on the search icon to expose search bar
1. Click on the hamburger icon to expose megamenu

## Deploy Notes
Import configuration as normal

### Testing on local
in the `docksal-local.env` file add/change the `PANTHEON_ENV` value to "pr-71" then run `fin init`. This will get the menu items from the test environment that cannot be added to DEV until the code is merged.

### CODE REVIEW

**Comment by jasonrsavino** [comment]
That was a repo access error. I added you via the Drupal team to the repo.

**Comment by Blanca-Esqueda** [comment]
@jasonrsavino 
I'm still having issues trying to have the site on my local.

I get the following errors:
'refresh command not found' when running fin init.
Screen Shot 2020-04-22 at 11 20 40 AM

And a class no found error:
Screen Shot 2020-04-22 at 11 20 25 AM

NOTE: if I run fin refresh,  then the site works.   I'm not sure if it is because a DB is downloaded or because something else...  maybe fixing the 'refresh command not found' will fix things...

**Comment by Blanca-Esqueda** [comment]
@jasonrsavino 

Followed the steps and not seeing the megamenu, search or sticky header.
There is an error of library not found,  but in code I can see the library.. so not sure what's happening:
Screen Shot 2020-04-29 at 9 03 33 AM

**Comment by Blanca-Esqueda** [comment]
@savino
I can see it is working on pr-71 environment.
it seems like the only missing thing is the sticky menu for desktop and mobile.

**Pull request merged**
