### PR TITLE
Adding User Account Fields

### PR DESCRIPTION
**Pull request by jasonrsavino**
## Description
User - Account 

Set up fields based on requirements in **Related Tickets** below

## Related Tickets

* [25888370: User - Account](https://kanopi.teamwork.com/#/tasks/25888370)

## Steps to Validate
1. Navigate to [User Login](http://pr-29-rooseveltedu.pantheonsite.io/user)
1. Log in as **admin** (credentials in LastPass)
1. Navigate to [Account Settings](http://pr-29-rooseveltedu.pantheonsite.io/admin/config/people/accounts/fields)
1. Note fields have been created based on [blueprint](https://docs.google.com/spreadsheets/d/1F6Y8rOghRSQqAGEcleseYnzEosZ01MN43eSndj--PWg/edit#gid=1590770110)
1. Navigate to [Add user](http://pr-29-rooseveltedu.pantheonsite.io/admin/people/create)
1. Note fields are displayed in form based on [blueprint](https://docs.google.com/spreadsheets/d/1F6Y8rOghRSQqAGEcleseYnzEosZ01MN43eSndj--PWg/edit#gid=1590770110)
1. Fill in available field
1. Click **Create new account** button
1. Note all the fields displayed (theme not implemented at this time)

### CODE REVIEW

**Comment by Blanca-Esqueda** [comment]
@jasonrsavino 
Everything looks good,   I just wasn't able to trigger the NET ID validation.  But if that one is going to be handled later on,  then this PR is good to merge.

**Comment by jasonrsavino** [comment]
@Blanca-Esqueda I added validation to the custom module. please review and merge

**Comment by Blanca-Esqueda** [comment]
@jasonrsavino 

NET ID validation still not complete.
If you try to save a user with NETID (without changing its NETID value) then the error: the Net ID field must be unique for each user   -- even when the NETID belongs only to that user.

**Comment by kwhite** [comment]
Hi @Blanca-Esqueda! Thanks for the review here. If you need @jasonrsavino  to make changes, can you please mark the PR by going to `Add Your Review`, requesting what needs doing, and then clicking `Request Changes` and submit the review? That way we're using a more formal process and it's clear where the PR is in the flow of review. Thank you!

**Pull request merged**
